"""
Script for measuring the RAM performance authomatically for all the mechanisms.
"""

import os
import csv
import numpy as np

# For storing the memory performance data.
folder = "memoryPerformance/"
ciphers = ["SABER=1", "KYBER=1", "NTRU=1", "NTRUP=1", "FRODO=1"]
massiffile = ["saber/saber", "kyber/kyber", "ntru/ntru", "ntrup/ntrup", "frodo/frodo"]
ext = ".out"
rm = "rm test"
make = "make test "
valgrind = "valgrind --tool=massif --stacks=yes --massif-out-file="
N = 1

def measureMemory():
    """
    Measure the memory consumption for each cipher.
    """
    for i in range(5):
        for j in range(N):
            # make with the memory option enabled, and desired operation
            # Remove test binary
            os.system(rm)
            cmd = make + "test " + ciphers[i] + " MEMORY=1 DEBUG=1"
            os.system(cmd)

            # Profile memory with valgrind
            cmd = valgrind + folder + massiffile[i] + "_" + str(j) + ext + " ./test"
            print(cmd)
            os.system(cmd)

def readThreeLines(file):
    file.readline()
    file.readline()
    file.readline()

def getTotalMemory(file):
    heap = int(file.readline().split("=")[1])
    heapExtra = int(file.readline().split("=")[1])
    stack = int(file.readline().split("=")[1])
    return heap + heapExtra + stack

def getMemoryUsageAll():
    """
    Read the output file generated by valgrind, and get the maximum amount of memory used per KEM
    """
    for i in range(4):
        # Get the array of values per operation
        memUsageAll = []
        for k in range(4):
            # Get the maximum value for each iteration
            memUsage = []   # Stores the max values for all files
            for j in range(N):
                fileN = folder + massiffile[i] + "1_" + str(j) + ext
                memUsageOp = []
                with open(fileN, "r") as file:
                    # Read the first three lines:
                    readThreeLines(file)
                    # Find the max value
                    for line in file:
                        # Search the following '#' character
                        if line[0] == "#":
                            # Read the following three lines
                            readThreeLines(file)
                            # Get the total amount of memory
                            total = getTotalMemory(file)
                            memUsageOp.append(total)
                memUsage.append(memUsageOp.copy())
        memUsageAll.append(memUsage.copy())
    return memUsageAll


def getMemoryUsageKEM():
    """
    Get the data of memory usage per KEM, all the operations
    """
    # For each kem
    totalValues = []
    for i in range(5):
        fileN = folder + massiffile[i] + "_TOTAL_0" + ext
        values = []
        print(fileN)
        with open(fileN, "r") as file:
            readThreeLines(file)
            for line in file:
                if line[0] == "#":
                    readThreeLines(file)
                    total = getTotalMemory(file)
                    values.append(total)
        totalValues.append(values.copy())
    return totalValues

def saveData(data, file, delimiter):
    m = np.array(data, dtype=object)
    mT = m.transpose()
    with open(file, "w") as csvfile:
        writer = csv.writer(csvfile, delimiter=delimiter)
        cipherS = ["LightSaber", "Kyber512", "NTRUhps2048509", "NTRULPr653", "Frodo640"]
        writer.writerow(cipherS)
        writer.writerows(mT)

if __name__ == '__main__':
    measureMemory()
    m = getMemoryUsageKEM()
    saveData(m, "memoryPerformance/memoryPerformance.csv", ",")
